apiVersion: apps/v1
kind: Deployment
metadata:
  name: converter-spring-boot-deployment
  labels:
    app: converter-spring-boot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: converter-spring-boot
  template:
    metadata:
      labels:
        app: converter-spring-boot
    spec:
      containers:
      - name: converter-spring-boot
        image: ielhaam/converter-spring-boot
        ports:
        - name: http
          containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: converter-spring-boot
  labels:
    app: converter-spring-boot
spec:
  selector:
    app: converter-spring-boot
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  type: LoadBalancer
          
      
